<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>omp_infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\omp-domain\omp-domain.csproj" />
    <ProjectReference Include="..\omp-application\omp-application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BrahmCQRS.Domain">
      <HintPath>..\libs\BrahmCQRS.Domain.dll</HintPath>
    </Reference>
    <Reference Include="BrahmCQRS.Application">
      <HintPath>..\libs\BrahmCQRS.Application.dll</HintPath>
    </Reference>
    <Reference Include="BrahmCQRS.Infrastructure">
      <HintPath>..\libs\BrahmCQRS.Infrastructure.dll</HintPath>
    </Reference>
    <Reference Include="BrahmCQRS.Shared">
      <HintPath>..\libs\BrahmCQRS.Shared.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.0.2" />
  </ItemGroup>

</Project>
